language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: Z3awcU93/xX8rwv+6uGEDdqZrPpJS4YW/47RScGciVHY5Cuwg9Wvyx0nYtNCKF0QxhapS86X/Zz/mKdYGxBKzuoGOBFIBXoSzWHzIL00UD+D6Z4STb4X7PWNmJBk4DIxHX3X3hAXLM41SRy/GLqpSH1YZZWvSvGmjk9diLjjnQ/d21chSrqyGCexpvc7YGmG81wFm+ZpmgUJ0jVbIP5napsMLIKycRKhtGFYgZxCmJxRLu4tuc1wrOg/K4SeBwWdgfBr7NWKiKhdJORVBowA4BoRIZ1Adyxmm5E6KUcQhgLl6m9BbguZ4Om/um4yEJyEP9NBFV4X+zb8XfHHtCgtvbDDk/e61fxMNB5BCYm1H7InCoZl8JeMZxKItb1XYGF5EXV5ZKD6STe1incNEMxxiRfl4iD3a+TVHJrPI2XNhFWw05AHau6UHlPaA2HO1mp9rNr/TFzV1MPr8uWf0+ye85+8nYhAmEEa52E+7mlV87bWajz9wszbTKeg75l41yEXcF/h/gwjLcMekNQ1vz3W6I+HaCUHHtqLdeTqGGX5TOwOCbz6xQDzURhxI+BjZfzIxpr/yK3JcjtwkXpmYiVJErsC4VbWHvQRlDxY/mRkpUwbLq/dF69eusszAmPESsYp7tjYjA2eHWK8XKO1V4v2aJuzQBiGMtD4Q7oEpskwPHs=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
