language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: e03yT1H8ydUL+M7eefxljcOCKT13iiomPJMuo0oEUhQf1GoBMY6paqt9bu9lu/pJPitYhtwkW1iLOY8dgY/0/szPoCfjby2sIKEfvItZcLieqwT+fbCqRLHTm+HuqsG4dqYPhWZCQZVP9hcXCzdRHYDPAEGQGNIQyiiZv16U+Vp/s0uP4joMGF+2/XKnrwtk2JDRnaBvL28Az9dZF7XsLjVgRl7gmwcwIvLZegoayNRrO5GURtePCpcBGDHm3z28e32qDnSheCckBhiFmphHFJauoyNI+ePx1uneVsb0xpJfopWpjxt/vuqMIUI+GTfZ0gwiVprWBdv00nMA+V4Ll52MOQYoSneOqiQkeVoFOONhEgrHVih2PMvsHeS/AoDIZayIC4vO9dU1a3yNdhZQpRk2LPuJZ14FeHB9xXOZHnNWnQeer58SMHXzdg0Yl4z0elKCx0tK7gMjB2LvsosjpkNXrGexGfuTNceu7I5XuZKKWOTqCVFH/OkcdbSPc2LUETsC//mrbAFQX/AIkR6M555cdCfs92JQq/jq/eT7kWqoxJMEj7GFqEwE0/A44aW5dV0L5OgUMCakj0t/Z7d+px8O4fzWCSUwcVF7QusLvYIVVy0jWCUcBXRMFF5no/AGbX9+N+Bxhb393YrcefCas93bM5SLRLfCnIDPY4ZKTQA=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
